name: CI

on:
  push:
    branches: [main, master]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
      - name: Install dependencies
        run: npm ci
      - name: Lint (CSS/JS)
        run: npm run check
      - name: Prettier check
        run: npm run format:check
        continue-on-error: true
      - name: Build
        run: npm run build
      - name: Serve _site for audits
        run: |
          npx http-server _site -p 8080 --silent &
          echo $! > server.pid
        shell: bash
      - name: Wait for server
        run: npx wait-on http://127.0.0.1:8080
      - name: Accessibility audit (Pa11y)
        run: npx pa11y-ci
      - name: Link check
        run: npx linkinator _site --recurse --skip "^mailto:"
      - name: Stop server
        if: always()
        run: |
          kill $(cat server.pid) || true
        shell: bash
